### PR TITLE
Rancher 2.4.8 support and fixes

### LINKED ISSUE #434: GCP cloud provider support
Hi, I'm trying to create a cluster in GCP with rancher2 terraform provider.

I've been using the following RKE config without an issue.
```
  cloud_provider:
    name: gce
    customCloudProvider: |-
      [global]
      project-id = myproject
      network-project-id = myproject
      network-name = default
      subnetwork-name = default
      regional = true
      multizone = true
```

 But the same configuration with rancher2 terraform provider generates the following errors.
```
# terraform configs
    cloud_provider {
      name = "gce"
      custom_cloud_provider = <<EOT
[global]
project-id = ${var.cloud_config.project_id}
network-project-id = ${var.cloud_config.network_project_id}
network-name = ${var.cloud_config.network_name}
subnetwork-name = ${var.cloud_config.subnet_name}
regional = true
multizone = true
      EOT
    }
```
```
Error: expected rke_config.0.cloud_provider.0.name to be one of [aws azure custom external openstack vsphere], got gce

  on ../../../onf-terraform/rancher/modules/cluster/acc-gcp/main.tf line 15, in resource "rancher2_cluster" "cluster":
  15: resource "rancher2_cluster" "cluster" {
```

If I put "custom" as name then `kubelet` fails to start due to unknown cloud provider name.
Any suggestion?

### LINKED ISSUE #436: App creation completes before app has finished installing
I have a Terraform module that declares two `rancher2_app` resources, where one depends on the other. I noticed that the second app is being created too early, before the first one has actually installed everything.

I can compare the  logged timestamp in Terraform of `module.my_apps.rancher2_app.istio: Creation complete after 2s` to the creation times of the app and one of the K8s resources in Rancher, and I see that the app was installed after the resource finished creation in Terraform.

Logs from `terraform apply` (timestamps are UTC-4).
```
Test 2020-08-28T11:38:45-04:00 logger.go:66: module.my_apps.rancher2_app.istio: Creating...
Test 2020-08-28T11:38:48-04:00 logger.go:66: module.my_apps.rancher2_app.istio: Creation complete after 2s [id=p-xxxxx:cluster-istio]
Test 2020-08-28T11:39:00-04:00 logger.go:66: module.my_apps.rancher2_app.my_service[0]: Creating...
<snip>
Test 2020-08-28T11:49:00-04:00 logger.go:66: module.my_apps.rancher2_app.my_service[0]: Still creating... [10m0s elapsed]
Test 2020-08-28T11:49:00-04:00 logger.go:66: Error: [ERROR] waiting for app (p-xxxxx:my-service) to be created: timeout while waiting for state to become 'active' (last state: 'installing', timeout: 10m0s)
```

Error message displayed in Rancher on the `my-service` app.
```
Failed to install app my-service. Error: validation failed: [unable to recognize "": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "Policy" in version "authentication.istio.io/v1alpha1", unable to recognize "": no matches for kind "ServiceEntry" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "ServiceRole" in version "rbac.istio.io/v1alpha1", unable to recognize "": no matches for kind "ServiceRoleBinding" in version "rbac.istio.io/v1alpha1"]
```

View of the `cluster-istio` app in the Rancher API. All timestamps here are after the `rancher2_app` resource completion finished.
```json
conditions": [
{
"lastUpdateTime": "2020-08-28T15:39:00Z",
"status": "True",
"type": "MetricExpressionDeployed"
},
{
"lastUpdateTime": "2020-08-28T15:39:00Z",
"status": "True",
"type": "Migrated"
},
{
"status": "Unknown",
"type": "UserTriggeredAction"
},
{
"lastUpdateTime": "2020-08-28T15:40:12Z",
"status": "True",
"type": "Installed"
},
{
"lastUpdateTime": "2020-08-28T15:40:12Z",
"status": "True",
"type": "ForceUpgrade"
},
{
"lastUpdateTime": "2020-08-28T16:21:36Z",
"status": "True",
"type": "Deployed"
}
],
"created": "2020-08-28T15:38:58Z"
```

One of the Istio CRDs that should have been installed before the `module.my_apps.rancher2_app.istio` resource finished creating.
```
> k get crd destinationrules.networking.istio.io
NAME                                   CREATED AT
destinationrules.networking.istio.io   2020-08-28T15:39:33Z
```

Terraform config.
```hcl
resource "rancher2_app" "istio" {
  catalog_name     = "system-library"
  template_name    = "rancher-istio"
  template_version = "1.4.1000"
  project_id       = rancher2_cluster_sync.this.system_project_id
  name             = "cluster-istio"
  target_namespace = rancher2_namespace.istio_system.name
  answers          = {<snip>}

  depends_on = [rancher2_app.cluster_autoscaler]
}

resource "rancher2_app" "my_service" {
  catalog_name     = local.my_catalog_name
  template_name    = "my-service"
  template_version = "0.1.2"
  project_id       = rancher2_cluster_sync.this.system_project_id
  name             = "my-service"
  target_namespace = rancher2_namespace.core_services[0].name

  depends_on = [
    rancher2_app.istio, # This app uses Istio CRDs
    rancher2_app.cluster_autoscaler
  ]
}
```

Using `terraform-provider-rancher2_v1.10.0`

### LINKED ISSUE #443: rancher2_certificate is not updated
When I update `rancher2_certificate`,  the `key` and `certs` are updated, but not other fields such as annotations, lables, expired date, etc. The bad part is, Rancher/K8S still uses the old cert (my guess is that maybe the Ingress depends on the annotation of the Secret to decide if it needs to update its config or not). I don't know if this is a bug from Rancher2 provider or Rancher.

Note: If I use the resource `kubernetes_secret`, the issue does not happen.

## How to reproduce the issue
- Use `rancher2_certificate` to add a certificate to Rancher
- Deploy an web application with the Ingress using the `rancher2_certificate` above
- Edit the contents of 2 arguments  `key` and `certs`  of the  `rancher2_certificate` resource to another valid values. Rerun terraform apply
- Access the website again and check the cert info again (e.g. showing certificate details on Google Chrome). It still uses the old one.

Please investigate and fix the issue.

### LINKED ISSUE #444: rancher2_project is trying to remove project_monitoring_input on every plan/apply
this is my config for a list of projects to be created

```
resource "rancher2_project" "projekte" {
  for_each                  = var.projekte
  name                      = each.key
  description               = each.value
  cluster_id                = data.rancher2_cluster.currentcluster.id
  enable_project_monitoring = true
  lifecycle {
    prevent_destroy = true
  }
}
```
and this happens if i run `terraform plan` again directly after doing a `terraform apply`

```
  ~ resource "rancher2_project" "projekte" {
        annotations               = {
            "authz.management.cattle.io/creator-role-bindings"                   = jsonencode(
                {
                    created  = [
                        "project-owner",
                    ]
                    required = [
                        "project-owner",
                    ]
                }
            )
            "field.cattle.io/overwriteAppAnswers"                                = "null"
            "lifecycle.cattle.io/create.mgmt-project-rbac-remove"                = "true"
            "lifecycle.cattle.io/create.project-namespace-auth_c-p5rfh"          = "true"
            "lifecycle.cattle.io/create.project-precan-alert-controller_c-p5rfh" = "true"
        }
        cluster_id                = "c-p5rfh"
        description               = "Portal Projekt"
        enable_project_monitoring = true
        id                        = "c-p5rfh:p-5frv7"
        labels                    = {
            "cattle.io/creator" = "norman"
        }
        name                      = "portal"
        wait_for_cluster          = false

      - project_monitoring_input {}
    }
```

or like this

```
  # rancher2_project.projekte["preisschild"] will be updated in-place
  ~ resource "rancher2_project" "projekte" {
        annotations               = {
            "authz.management.cattle.io/creator-role-bindings"                   = jsonencode(
                {
                    created  = [
                        "project-owner",
                    ]
                    required = [
                        "project-owner",
                    ]
                }
            )
            "field.cattle.io/overwriteAppAnswers"                                = jsonencode(
                {
                    answers = {
                        grafana.persistence.enabled               = "false"
                        grafana.persistence.size                  = "10Gi"
                        grafana.persistence.storageClass          = "default"
                        prometheus.persistence.enabled            = "false"
                        prometheus.persistence.size               = "50Gi"
                        prometheus.persistence.storageClass       = "default"
                        prometheus.persistent.useReleaseName      = "true"
                        prometheus.resources.core.limits.cpu      = "1000m"
                        prometheus.resources.core.limits.memory   = "1000Mi"
                        prometheus.resources.core.requests.cpu    = "750m"
                        prometheus.resources.core.requests.memory = "750Mi"
                        prometheus.retention                      = "12h"
                    }
                    version = "0.0.7"
                }
            )
            "lifecycle.cattle.io/create.mgmt-project-rbac-remove"                = "true"
            "lifecycle.cattle.io/create.project-namespace-auth_c-6r4hc"          = "true"
            "lifecycle.cattle.io/create.project-precan-alert-controller_c-6r4hc" = "true"
        }
        cluster_id                = "c-6r4hc"
        description               = "Preisschild Projekt"
        enable_project_monitoring = true
        id                        = "c-6r4hc:p-gkl8d"
        labels                    = {
            "cattle.io/creator" = "norman"
        }
        name                      = "preisschild"
        wait_for_cluster          = false

      - project_monitoring_input {
          - answers = {
              - "grafana.persistence.enabled"               = "false"
              - "grafana.persistence.size"                  = "10Gi"
              - "grafana.persistence.storageClass"          = "default"
              - "prometheus.persistence.enabled"            = "false"
              - "prometheus.persistence.size"               = "50Gi"
              - "prometheus.persistence.storageClass"       = "default"
              - "prometheus.persistent.useReleaseName"      = "true"
              - "prometheus.resources.core.limits.cpu"      = "1000m"
              - "prometheus.resources.core.limits.memory"   = "1000Mi"
              - "prometheus.resources.core.requests.cpu"    = "750m"
              - "prometheus.resources.core.requests.memory" = "750Mi"
              - "prometheus.retention"                      = "12h"
            } -> null
          - version = "0.0.7" -> null
        }

        timeouts {}
    }
```

I did not change or edit those values...

### PR DESCRIPTION
**Pull request by rawmind0**
This PR contains fixes:
* `rke_config.cloud_provider.name` argument value is no validated anymore. Closes #434 
* `rancher2_certificate` resource update. Closes #443 
* False diff if `rancher2_project.project_monitoring_input` not specified. Closes #444 
* Fix `rancher2_token.ttl` argument to work properly on Rancher up to v2.4.7. ttl passed again on miliseconds.
* Fix `rancher2_namespace.resource_quota` argument to computed
* Fix `rancher2_app` resource to wait until created/updated. Closes #436 
* Added `rancher2_cluster_sync.state_confirm` argument to wait until active status is confirmed a number of times

### CODE REVIEW

File: rancher2/resource_rancher2_app.go [hunk 1]
```diff
@@ -178,13 +190,26 @@ func resourceRancher2AppUpdate(d *schema.ResourceData, meta interface{}) error {
...
-			Target:     []string{"active"},
+			Target:     []string{"installing"},
 			Refresh:    appStateRefreshFunc(client, id),
 			Timeout:    d.Timeout(schema.TimeoutUpdate),
 			Delay:      1 * time.Second,
 			MinTimeout: 3 * time.Second,
 		}
 		_, waitErr := stateConf.WaitForState()
+		if waitErr != nil {
+			return fmt.Errorf(
```
Comment (armsnyder) [inline rancher2/resource_rancher2_app.go]: One possible issue here is if the app actually finishes installing before the first refresh. I'd suggest setting a shorter timeout on this first `StateChangeConf` and log/ignore the `WaitForState` error here. That is unless there's a greater possibility that Rancher is responding "active" before install begins for a potentially long or infinite time.

Comment (rawmind0) [reply rancher2/resource_rancher2_app.go]: App should be on `installing` or `deploying` state before be created or updated. There is no delay on first state check, and refresh interval is adjusted to 2s, helm installation should last less than 2s to be avoided.

Comment (armsnyder) [reply rancher2/resource_rancher2_app.go]: Ok, sounds good. One more thing though:

In the block of code above this, you have a conditional call to the Rancher API, so it is possible that the resource is updated without calling the Rancher API. In that case this `WaitForState` will fail because the app was not modified.

Comment (rawmind0) [reply rancher2/resource_rancher2_app.go]: That's true, thanks. Updated

**Review by deniseschannon — APPROVED** [review]

File: rancher2/resource_rancher2_app.go (hunk 1 above)
Comment (rawmind0) [reply rancher2/resource_rancher2_app.go]: Finally i've changed the scope. App first is waiting until it's not transitioning, and then checking for active state. This should be more accurate.
