### PR TITLE
Fixed issue with hetzner variable naming

### LINKED ISSUE #567: Naming failure in Hetzner-Cloud node templates
Seems like i established a naming issue in #522.
Instead of `private_network` i have named the template-variable `private_networks`.
Due to this error, the variable is not set in Rancher.

I will fix this later.

For more details see:
https://github.com/alexzimmer96/rancher-hcloud/issues/11

### PR DESCRIPTION
**Pull request by alexzimmer96**
This PR removes corrects a wrong named variable in the Hetzner-Cloud node template. Instead of `use_private_network` the variable was named `use_private_networks`.

I decided to introduce a new variable with the correct name and mark the old one as deprecated. I have also fixed the mapping, so that the wrong named variable will be mapped right. However, the new variable will win over a the wrong named one, if its set.

Fixes rancher/terraform-provider-rancher2#567

### CODE REVIEW

**Review by rawmind0 — COMMENTED** [review]
@alexzimmer96 , as flatten and expander were pointing to a non existent parameter,  i guess the parameter was never working. So i'm not sure if "bad" named parameter should remain here as deprecated.

What do you think just rename variable properly at `docs/resources/node_template.md` and `rancher2/schema_node_template_hetzner.go`  and let `rancher2/structure_node_template_hetzner.go`  untouched??

**Comment by alexzimmer96** [comment]
@rawmind0 I think this would also work. I did not know which solution you prefer. Because of that i wanted to left the current spec untouched and just make it work. Should i create a new PR or fix it in this one?

**Comment by rawmind0** [comment]
@alexzimmer96 , i'd prefer scope the PR as a parameter typo instead of a deprecated  parameter, due to it was not working before. If you agree,  just fix the PR renaming variable properly at `docs/resources/node_template.md` and `rancher2/schema_node_template_hetzner.go` and let `rancher2/structure_node_template_hetzner.go` untouched.

**Review by paraglade — APPROVED** [review]
LGTM

**Comment by rawmind0** [comment]
@alexzimmer96 , any update here?? We are cutting a new tfp release next week, and we'd like to include this PR if possible

**Comment by alexzimmer96** [comment]
@rawmind0 I am positive to finish this until Friday.

**Comment by rawmind0** [comment]
> @rawmind0 I am positive to finish this until Friday.

@alexzimmer96 , sounds good, thanks.

**Comment by rawmind0** [comment]
@alexzimmer96 , any update here??

**Comment by alexzimmer96** [comment]
Hi @rawmind0 
I've updated this PR. Would you check if this matches your expectations.

**Review by rawmind0 — COMMENTED** [review]
Thanks for the update @alexzimmer96 

It seems there is another type mismatch at the Hetzner node_template driver, reported by issue https://github.com/rancher/terraform-provider-rancher2/issues/607 

The [`networks` and `volumes` arguments](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_node_template_hetzner.go#L18) at this tf provider,  are defined as `string` separated by `,`, but the fields at the [Hetzner docker machine driver](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/master/driver.go#L41) are defined as `[]string`. 

Proposed patch: 
- `rancher2/schema_node_template_hetzner.go`
[type hetznerConfig struct](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_node_template_hetzner.go#L13)
```
-	Networks          string `json:"networks,omitempty" yaml:"networks,omitempty"`
+	Networks          []string `json:"networks,omitempty" yaml:"networks,omitempty"`
...
-	Volumes           string `json:"volumes,omitempty" yaml:"volumes,omitempty"`
+	Volumes           []string `json:"volumes,omitempty" yaml:"volumes,omitempty"`
```

- `rancher2/structure_node_template_hetzner.go`
[func flattenHetznerConfig](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_node_template_hetzner.go#L5)
```
	if len(in.Networks) > 0 {
-		obj["networks"] = in.Networks
+		obj["networks"] = strings.Join(in.Networks, ", ")
	}
...
	if len(in.Volumes) > 0 {
-		obj["volumes"] = in.Volumes
+		obj["volumes"] = strings.Join(in.Volumes, ", ")
	}
```
[func expandHetznercloudConfig](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_node_template_hetzner.go#L46)
```
	if v, ok := in["networks"].(string); ok && len(v) > 0 {
-		obj.Networks = v
+		obj.Networks = strings.Split(v, ",")
	}
...
	if v, ok := in["volumes"].(string); ok && len(v) > 0 {
-		obj.Volumes = v
+		obj.Volumes = strings.Split(v, ",")
	}
```

Do you think it'd be possible to include the patch at this PR, or do you prefer to submit a new one??

**Comment by alexzimmer96** [comment]
Hi @rawmind0 
Thanks for preparing this. I've added your proposed changes into this pull request.

File: rancher2/structure_node_template_hetzner.go [hunk 1]
```diff
@@ -25,7 +27,7 @@ func flattenHetznerConfig(in *hetznerConfig) []interface{} {
 	}
 
 	if len(in.Networks) > 0 {
-		obj["networks"] = in.Networks
+		obj["networks"] = strings.Join(in.Networks, ", ")
```
Comment (rawmind0) [inline rancher2/structure_node_template_hetzner.go]: Typo here defining separator, 
```
-		obj["networks"] = strings.Join(in.Networks, ", ")
+		obj["networks"] = strings.Join(in.Networks, ",")
```

File: rancher2/structure_node_template_hetzner.go [hunk 2]
```diff
@@ -35,7 +37,7 @@ func flattenHetznerConfig(in *hetznerConfig) []interface{} {
 	}
 
 	if len(in.Volumes) > 0 {
-		obj["volumes"] = in.Volumes
+		obj["volumes"] = strings.Join(in.Volumes, ", ")
```
Comment (rawmind0) [inline rancher2/structure_node_template_hetzner.go]: Typo here defining separator, 
```
-		obj["volumes"] = strings.Join(in.Volumes, ", ")
+		obj["volumes"] = strings.Join(in.Volumes, ",")
```

**Review by rawmind0 — CHANGES_REQUESTED** [review]

**Comment by alexzimmer96** [comment]
@rawmind0 Should be fixed now

**Review by rawmind0 — APPROVED** [review]
Thanks @alexzimmer96 

LGTM

**Comment by rawmind0** [comment]
Issue https://github.com/rancher/terraform-provider-rancher2/issues/607
