### PR TITLE
Verify desired_size in EKSConfig NodeGroups

### LINKED ISSUE #989: TF is unable to manage downstream EKS cluster resource w/ `desired_size=0, max_size=1, min_size=0`
When provisioning a downstream EKS cluster via RancherUI, if `desired_size=0, max_size=1, min_size=0`, cluster will provision until it reaches a `Waiting` state, at which point it will remain in that state until nodes are added.  This is expected behavior.

With TF rancher2 provider, when attempting the scenario outlined above, once cluster reaches `Waiting` state, where it will remain until nodes are added, TF reports cluster resource as `still creating`.  This will not resolve.

When manually stopping TF from continuing its execution, modifying main.tf to reflect desired nodes, and running terraform apply again, this results in an error: `cluster already exists`.

It is impossible at this point for TF to manage the resource it has created.  This issue was created to address this circumstance.

At this point, cluster will only come up active by scaling up nodes through Rancher, without the use of TF.

**Additional Context**
Terraform is successful when initially deploying cluster w/ nodes, then scaling down to 0 nodes, and back up.  No issues, expected behavior.

Issue is only experienced when initially attempting to provision EKS w/ 0 nodes.

Screenshots:
187995647-22d9314e-fbd8-4660-b66c-9ea278c74293

---

It is my impression, that under this circumstance, allowing TF to recognize this `Waiting` state as the end of its resource creation, could address this behavior and resolve the issue.

### PR DESCRIPTION
**Pull request by mjura**
Issue: https://github.com/rancher/terraform-provider-rancher2/issues/989

### CODE REVIEW

**Review by salasberryfin — APPROVED** [review]
LGTM

File: rancher2/resource_rancher2_cluster.go [hunk 1]
```diff
@@ -143,6 +143,9 @@ func resourceRancher2ClusterCreate(d *schema.ResourceData, meta interface{}) err
 	cluster.EnableClusterMonitoring = false
 	newCluster := &Cluster{}
 	if cluster.EKSConfig != nil && !cluster.EKSConfig.Imported {
+		if !checkClusterEKSConfigV2NodeGroupsDesiredSize(cluster) {
+			return fmt.Errorf("[ERROR] can't create %s EKS cluster with desired_size = 0", cluster.Name)
```
Comment (furkatgofurov7) [inline rancher2/resource_rancher2_cluster.go]:
```suggestion
			return fmt.Errorf("[ERROR] can't create %s EKS cluster with node group desired_size = 0", cluster.Name)
```

**Review by furkatgofurov7 — COMMENTED** [review]
LGTM, small nitty:

**Review by furkatgofurov7 — APPROVED** [review]
